# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PubPress' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PubPress
pod 'Alamofire'
pod 'SDWebImage'
pod 'SwiftyJSON'
pod 'Toast-Swift', '~> 2.0.0'
pod 'CarbonKit'
pod 'Material'
pod 'Stripe'
end
